/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.marketing.list.ui;

import fi.marketing.list.Operator;
import fi.marketing.list.logic.lists.MarketingList;
import fi.marketing.list.FileReader;
import java.io.InputStream;

public class DashboardUI extends javax.swing.JFrame {

    private Operator oper;

    public DashboardUI(Operator op) {
        oper = op;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        contactListName = new javax.swing.JTextField();
        nameNewMarketingList = new javax.swing.JTextField();
        addContactListButton = new javax.swing.JButton();
        createMarketingListButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        selectType = new javax.swing.JComboBox<>();
        fileName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        infoAreaStatistics = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");

        contactListName.setText("Give a name to new Contact List");

        nameNewMarketingList.setText("Give a name to new Marketing List");

        addContactListButton.setText("Add");
        addContactListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContactListButtonActionPerformed(evt);
            }
        });

        createMarketingListButton.setText("Create");
        createMarketingListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMarketingListButtonActionPerformed(evt);
            }
        });

        infoArea1.setColumns(20);
        infoArea1.setRows(5);
        jScrollPane1.setViewportView(infoArea1);

        infoArea2.setColumns(20);
        infoArea2.setRows(5);
        jScrollPane2.setViewportView(infoArea2);

        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane3.setViewportView(resultArea);

        selectType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Collect Phone Numbers", "Collect Email Addresses" }));

        fileName.setText("Type the File Name");

        infoAreaStatistics.setColumns(20);
        infoAreaStatistics.setRows(5);
        jScrollPane4.setViewportView(infoAreaStatistics);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(selectType, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(createMarketingListButton))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(nameNewMarketingList, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contactListName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addContactListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addContactListButton)
                            .addComponent(contactListName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(nameNewMarketingList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createMarketingListButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addContactListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContactListButtonActionPerformed
        if (evt.getSource() == addContactListButton && fileName.getText().endsWith(".txt")) {
            InputStream is = getClass().getClassLoader().getResourceAsStream(fileName.getText());
            FileReader just = oper.fileReaderInputStream(is);
            long startTime = System.currentTimeMillis();
            oper.matchAContactListToCustomers(just, contactListName.getText());
            long endTime = System.currentTimeMillis();
            infoArea1.setText(oper.printTime(startTime, endTime) + "\n" + "There is " + oper.getContactCountNumber() + " rows of contact data to be put on the list " + contactListName.getText() + ".");
            infoAreaStatistics.setText("There are " + oper.getCustomers().numberOfCustomers() + " customers in the system. \n Emails: " + oper.getCustomers().getNumberOfEmails() + "\n Phone numbers: " + oper.getCustomers().getNumberOfPhoneNumbers());
        }
    }//GEN-LAST:event_addContactListButtonActionPerformed

    private void createMarketingListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMarketingListButtonActionPerformed
        if (evt.getSource() == createMarketingListButton) {
            if (selectType.getSelectedIndex() == 0) {
                setTextAndType(infoArea2, resultArea, fi.marketing.list.logic.Type.phone);
            } else if (selectType.getSelectedIndex() == 1) {
                setTextAndType(infoArea2, resultArea, fi.marketing.list.logic.Type.email);
            }
        }
    }//GEN-LAST:event_createMarketingListButtonActionPerformed

    private void setTextAndType(javax.swing.JTextArea two, javax.swing.JTextArea three, fi.marketing.list.logic.Type tp) {
        MarketingList list = oper.createAMarketingList(nameNewMarketingList.getText(), tp);
        two.setText(oper.getWrittenCount() + " rows were saved to the " + nameNewMarketingList.getText() + ".txt file.");
        three.setText(list.printString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContactListButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField contactListName;
    private javax.swing.JButton createMarketingListButton;
    private javax.swing.JTextField fileName;
    private javax.swing.JTextArea infoArea1;
    private javax.swing.JTextArea infoArea2;
    private javax.swing.JTextArea infoAreaStatistics;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nameNewMarketingList;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JComboBox<String> selectType;
    // End of variables declaration//GEN-END:variables
}
